name: TG Shop Bot

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 */3 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    concurrency:
      group: tg-bot-instance
      cancel-in-progress: true

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装 Python 依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 安装 Playwright 浏览器
        run: |
          playwright install --with-deps chromium

      - name: 启动机器人
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          ADMIN_URL: ${{ secrets.ADMIN_URL }}
          ADMIN_USER: ${{ secrets.ADMIN_USER }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASS }}

          SINGLE_ADMIN_URL: ${{ secrets.SINGLE_ADMIN_URL }}
          SINGLE_ADMIN_USER: ${{ secrets.SINGLE_ADMIN_USER }}
          SINGLE_ADMIN_PASS: ${{ secrets.SINGLE_ADMIN_PASS }}

          JJ_ADMIN_URL: ${{ secrets.JJ_ADMIN_URL }}
          JJ_ADMIN_USER: ${{ secrets.JJ_ADMIN_USER }}
          JJ_ADMIN_PASS: ${{ secrets.JJ_ADMIN_PASS }}
          JJ_2FA_SECRET: ${{ secrets.JJ_2FA_SECRET }}

        run: |
          python main.py
